[package]
name = "Easebuild"
version = "0.1.0"
edition = "2021"

[dependencies]
anstyle = "1.0.8"
clap = { version = "4.5.10", features = ["derive", "cargo"] }
colored = "2.1.0"
mlua = { version = "0.9.9", features = ["luau", "luau-jit", "async", "macros", "serialize"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
sysinfo = "0.30.13"
